stages:
  prepare:
    cmd: python3 scr/prepare.py
    deps:
    - scr/prepare.py
    params:
    - prepare.categories
    outs:
    - data/prepared
  featurize:
    cmd: python3 scr/featurize.py data/prepared data/features
    deps:
    - data/prepared
    - scr/featurize.py
    outs:
    - data/features
  train:
    cmd: python3 scr/train.py data/features data/models/model.pkl
    deps:
    - scr/train.py
    params:
    - train.alpha
    outs:
    - data/models/model.pkl
